// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-WW2hiME79tWUTyQkyTRTOgP0ncBEHk',
    appId: '1:591311597406:web:c985b53a7b8129f7d8e9cf',
    messagingSenderId: '591311597406',
    projectId: 'wanna-wanna',
    authDomain: 'wanna-wanna.firebaseapp.com',
    databaseURL: 'https://wanna-wanna.firebaseio.com',
    storageBucket: 'wanna-wanna.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoL-QluDTncvWeSxSjqOxm018uSaExk0',
    appId: '1:591311597406:android:e06834c9c1aaade7d8e9cf',
    messagingSenderId: '591311597406',
    projectId: 'wanna-wanna',
    databaseURL: 'https://wanna-wanna.firebaseio.com',
    storageBucket: 'wanna-wanna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKG2fxthq2T0KReC_QDPA_OzKT3-D6Qk',
    appId: '1:591311597406:ios:a138854be2673ba5d8e9cf',
    messagingSenderId: '591311597406',
    projectId: 'wanna-wanna',
    databaseURL: 'https://wanna-wanna.firebaseio.com',
    storageBucket: 'wanna-wanna.appspot.com',
    iosClientId: '591311597406-u4ds3f6ll5r8ai5peijm6cm1p3teldfp.apps.googleusercontent.com',
    iosBundleId: 'com.leechylabs.wannawanna',
  );
}
